development: &default
  adapter: mysql2
  database: solidsteel_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: solidsteel_test

staging:
  adapter: mysql2
  database: solidsteel_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *default
  database: solidsteel_development